"""IFB Washer Local - Async Python library for local IFB washing machine control."""

from .client import IFBWasherClient
from .const import (
    DEFAULT_PORT,
    ERROR_CODES,
    FAMILY_PROGRAM_MATRICES,
    PROGRAM_CODES_742,
    PROGRAM_CODES_FRONT_LOAD,
    PROGRAM_CODES_TOP_LOAD,
    PROGRAM_CODES_WASHER_DRYER,
    SPIN_SPEED_OPTIONS,
    STATE_LABELS,
    TELEMETRY_SIGNATURES,
    TEMPERATURE_OPTIONS,
    ApplianceFamily,
    MachineState,
    ProgramCapabilities,
    ProgramSignature,
)
from .exceptions import (
    IFBConnectionError,
    IFBError,
    IFBProtocolError,
    IFBTimeoutError,
)
from .profiler import (
    calibrate_appliance_detailed,
    calibrate_appliance_quick,
    calibrate_appliance_simple,
    deserialize_capabilities_map,
    extract_profile_metadata,
    probe_single_program,
    save_profile_backup,
    serialize_capabilities_map,
)
from .protocol import (
    WasherState,
    build_child_lock_command,
    build_fixed_command,
    build_program_selection,
    build_status_query,
    build_user_option_command,
    compute_checksums,
    detect_program_from_telemetry,
    parse_status_frame,
)

__all__ = [
    "ApplianceFamily",
    "DEFAULT_PORT",
    "ERROR_CODES",
    "FAMILY_PROGRAM_MATRICES",
    "IFBConnectionError",
    "IFBError",
    "IFBProtocolError",
    "IFBTimeoutError",
    "IFBWasherClient",
    "MachineState",
    "PROGRAM_CODES_742",
    "PROGRAM_CODES_FRONT_LOAD",
    "PROGRAM_CODES_TOP_LOAD",
    "PROGRAM_CODES_WASHER_DRYER",
    "ProgramCapabilities",
    "ProgramSignature",
    "SPIN_SPEED_OPTIONS",
    "STATE_LABELS",
    "TELEMETRY_SIGNATURES",
    "TEMPERATURE_OPTIONS",
    "WasherState",
    "build_child_lock_command",
    "build_fixed_command",
    "build_program_selection",
    "build_status_query",
    "build_user_option_command",
    "calibrate_appliance_detailed",
    "calibrate_appliance_quick",
    "calibrate_appliance_simple",
    "compute_checksums",
    "deserialize_capabilities_map",
    "detect_program_from_telemetry",
    "extract_profile_metadata",
    "parse_status_frame",
    "probe_single_program",
    "save_profile_backup",
    "serialize_capabilities_map",
]

